online_shop/cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('add/<product_id>/', add_to_cart, name='add_to_cart'),
    path('remove/<product_id>/', remove_from_cart, name='remove_from_cart'),
    path('list/', show_cart, name='show_cart'),
]

online_shop/manager/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import *

app_name = 'manager'

urlpatterns = [
    path('', TemplateView.as_view(template_name='base_page.html'), name='main-page'),
    path('category/', ListCategory.as_view(template_name='list-category.html'), name='list-category'),
    path('product/', ListProduct.as_view(template_name='list-product.html'), name='list-product'),
    path('create-category/', CreateCategory.as_view(), name='create-category'),
    path('create-product/', CreateProduct.as_view(), name='create-product'),
    path('<int:pk>/edit-category/', EditCategory.as_view(), name='edit-category'),
    path('<int:pk>/delete-category/', DeleteCategory.as_view(), name='delete-category'),
    path('<int:pk>/edit-product/', EditProduct.as_view(), name='edit-product'),
    path('<int:pk>/delete-product/', DeleteProduct.as_view(), name='delete-product'),
    path('order/', ListOrder.as_view(), name='list-order'),

]

online_shop/online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('x/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('manager/', include('manager.urls', namespace='manager')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_shop/manager/models.py
from django.db import models

# Create your models here.

online_shop/manager/forms.py
# from django import forms
#
# from shop.models import Product
#
#
# class CreateProductForm(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = ['name', 'image', 'price', 'description', 'category', 'slug']

online_shop/manager/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from shop.models import *
from .forms import *
from orders.models import Order


# crud Category Product
class ListCategory(ListView):
    model = Category
    context_object_name = 'categories'
    # print(category.products)

    def get_queryset(self):
        return Category.objects.order_by('name')


class ListProduct(ListView):
    model = Product
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.order_by('category')


class CreateCategory(CreateView):
    model = Category
    fields = ['name']
    template_name = 'create-category.html'

    success_url = '/manager/'
    # def get_success_url(self):
    #     return redirect('manager:list-category')


class EditCategory(UpdateView):
    model = Category
    fields = ['name']
    template_name = 'edit-category.html'

    success_url = '/manager/'
    # def get_success_url(self):
    #     return redirect('/')


class DeleteCategory(DeleteView):
    model = Category
    template_name = 'delete-category.html'
    success_url = reverse_lazy('manager:list-category')


class CreateProduct(CreateView):
    model = Product
    fields = ['name', 'image', 'description', 'price', 'category']
    # form_class = CreateProductForm
    template_name = 'create-product.html'
    
    # def form_valid(self, form):
    #     image = form.cleaned_data['image']
    #     return super().form_valid(form)

    # def get_success_url(self):
    #     return redirect('manager:create-product.html')


class EditProduct(UpdateView):
    model = Product
    fields = ['name', 'description', 'image', 'price', 'category']
    template_name = 'edit-product.html'

    
class DeleteProduct(DeleteView):
    model = Product
    success_url = reverse_lazy('manager:list-product')
    template_name = 'delete-product.html'


class ListOrder(ListView):
    model = Order
    template_name = 'list-order.html'
    context_object_name = 'orders'

online_shop/manager/templates/base_page.html
{% extends 'base.html' %}
{% block content %}
<ul>
    <li><a href="{% url 'manager:list-order' %}">order</a></li>
    <li><a href="{% url 'manager:list-category' %}">category</a></li>
    <li><a href="{% url 'manager:list-product' %}">product</a></li>
<!--    <li><a href=""></a></li>-->
</ul>
{% endblock %}

online_shop/manager/templates/create-category.html
{% extends 'base.html' %}

{% block content %}
<h2>Create Category</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="save">
</form>
{% endblock %}

online_shop/manager/templates/create-product.html
{% extends 'base.html' %}

{% block content %}
<h2>Create Product</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

online_shop/manager/templates/delete-category.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>Are you sure delete {{ object }}</h3>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

online_shop/manager/templates/delete-product.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>Are you sure delete {{ object }}</h3>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

online_shop/manager/templates/edit-category.html
{% extends 'base.html' %}

{% block content %}
<h3>Edit category</h3>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="save">
</form>
{% endblock %}

online_shop/manager/templates/edit-product.html
{% extends 'base.html' %}

{% block content %}
<h3>Edit product</h3>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="save">
</form>
{% endblock %}

online_shop/manager/templates/list-category.html
{% extends 'base.html' %}

{% block content %}
<h2>lists in category</h2>
<h3><a href="{% url 'manager:list-product' %}">to product</a></h3>
<h5><a href="{% url 'manager:create-category' %}">create category</a></h5>
{% for category in categories %}
<div>{{ category.name }}
    <a href="{% url 'manager:edit-category' category.pk %}">edit</a>
    <a href="{% url 'manager:delete-category' category.pk %}">delete</a>
</div>
{% endfor %}
{% endblock %}

online_shop/manager/templates/list-order.html
{% extends 'base.html' %}
{% block content %}
<h2>Order list</h2>
{% for order in orders %}
    <p>{{ order }} <a href="">delete</a></p>

{% endfor %}
{% endblock %}

online_shop/manager/templates/list-product.html
{% extends 'base.html' %}

{% block content %}
<h2>list of products</h2>
<h3><a href="{% url 'manager:list-category' %}">to category</a></h3>
<h5><a href="{% url 'manager:create-product' %}">create product</a></h5>
{% for product in products %}
    <p>{{ product.name }}
        <a href="{% url 'manager:edit-product' product.pk %}">edit</a>
        <a href="{% url 'manager:delete-product' product.pk %}">delete</a>
    </p>
{% endfor %}
{% endblock %}